name: Deploy Images

on:
  push:
    branches:
      - development
    workflow_dispatch:
    # manual dispatch allowed

jobs:
  base:
    name: "Deploy Image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.description="SSH Dev-Container"
            org.opencontainers.image.licenses=MIT
          tags: |
            ghcr.io/${{ github.repository_owner }}/ssh-dev-container:latest